# Starts NeonRuntime without a window, lets it render its scene, and looks at
# the exit code and at the images it saved.

include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/scripts/run-application.cmake")

# run_headless(<argument>...)
function(run_headless)
  run(--headless-renderer --time-step 0.016667 ${ARGN})

  set(EXIT_CODE "${EXIT_CODE}" PARENT_SCOPE)
  set(OUTPUT "${OUTPUT}" PARENT_SCOPE)
endfunction()

# expect_image_size(<path> <width> <height>): what the header of the PNG says
function(expect_image_size PATH WIDTH HEIGHT)
  expect_image("${PATH}")

  file(READ "${DIRECTORY}/${PATH}" HEADER OFFSET 16 LIMIT 8 HEX)
  math(EXPR WIDTH_HEX "${WIDTH}" OUTPUT_FORMAT HEXADECIMAL)
  math(EXPR HEIGHT_HEX "${HEIGHT}" OUTPUT_FORMAT HEXADECIMAL)
  string(SUBSTRING "${WIDTH_HEX}" 2 -1 WIDTH_HEX)
  string(SUBSTRING "${HEIGHT_HEX}" 2 -1 HEIGHT_HEX)
  string(REPEAT "0" 8 ZEROS)
  string(SUBSTRING "${ZEROS}${WIDTH_HEX}" 0 -1 PADDED)
  string(LENGTH "${WIDTH_HEX}" WIDTH_LENGTH)
  math(EXPR CUT "8 - ${WIDTH_LENGTH}")
  string(SUBSTRING "${ZEROS}" 0 ${CUT} WIDTH_PAD)
  string(LENGTH "${HEIGHT_HEX}" HEIGHT_LENGTH)
  math(EXPR CUT "8 - ${HEIGHT_LENGTH}")
  string(SUBSTRING "${ZEROS}" 0 ${CUT} HEIGHT_PAD)

  if (NOT HEADER STREQUAL "${WIDTH_PAD}${WIDTH_HEX}${HEIGHT_PAD}${HEIGHT_HEX}")
    fail("Expected ${PATH} to be ${WIDTH} by ${HEIGHT} pixels, its header says ${HEADER}")
  endif ()
endfunction()

if (CASE STREQUAL "window-size-and-render-scale")
  # 640 by 360 points at two pixels a point is 1280 by 720 pixels
  run_headless(--frames 2 --output-dir shots --screenshot output://frame.png --window-size 640x360 --render-scale 2
          --ui assets://ui/hud.ui.yml)
elseif (CASE STREQUAL "settings-menu-with-input")
  # a name is typed, and the dropdown of the quality is opened. The steps
  # are on lines of their own, since a semicolon is a list to CMake
  set(SCRIPT "20: pointer 1000 321\n21: click\n23: text Lovelace\n30: pointer 1000 439\n31: click")
  run_headless(--output-dir shots --screenshot output://frame.png --screenshot-at 20,40
          --scene assets://scenes/settings-demo.scene.yml --input "${SCRIPT}")
elseif (CASE STREQUAL "ui-scale")
  run_headless(--frames 2 --output-dir shots --screenshot output://plain.png --ui assets://ui/hud.ui.yml)
  set(PLAIN_EXIT_CODE "${EXIT_CODE}")
  run_headless(--frames 2 --output-dir shots --screenshot output://large.png --ui assets://ui/hud.ui.yml --ui-scale 1.5)
elseif (CASE STREQUAL "last-frame")
  run_headless(--frames 3 --output-dir shots --screenshot output://frame.png)
elseif (CASE STREQUAL "listed-frames")
  run_headless(--output-dir shots --screenshot output://today/frame.png --screenshot-at 3,1)
elseif (CASE STREQUAL "without-screenshot")
  run_headless(--frames 2)
elseif (CASE STREQUAL "screenshot-for-the-user")
  run_headless(--frames 1 --screenshot user://shots/frame.png)
elseif (CASE STREQUAL "output-folder-cannot-be-used")
  # a file is where the folder would have to be
  file(WRITE "${DIRECTORY}/taken" "a file, not a folder")
  run_headless(--frames 1 --output-dir taken --screenshot output://frame.png)
elseif (CASE STREQUAL "user-interface")
  # the same frame without and with a user interface on top of it
  run_headless(--frames 2 --output-dir shots --screenshot output://plain.png)
  set(PLAIN_EXIT_CODE "${EXIT_CODE}")
  run_headless(--frames 2 --output-dir shots --screenshot output://frame.png --ui assets://ui/hud.ui.yml)
elseif (CASE STREQUAL "user-interface-of-a-scene")
  run_headless(--frames 2 --output-dir shots --screenshot output://frame.png
          --scene assets://scenes/hud-demo.scene.yml)
elseif (CASE STREQUAL "user-interface-that-is-missing")
  run_headless(--frames 2 --output-dir shots --screenshot output://frame.png --ui assets://ui/missing.ui.yml)
elseif (CASE STREQUAL "pause-menu")
  # pause is pressed, the menu is closed with cancel, and pressed again
  set(SCRIPT "5: hold pause\n20: hold ui-cancel\n30: hold pause")
  run_headless(--output-dir shots --screenshot output://frame.png --screenshot-at 3,10,25,40
          --scene assets://scenes/hud-demo.scene.yml --input "${SCRIPT}")
elseif (CASE STREQUAL "input-map-of-the-project")
  run_headless(--frames 1)
elseif (CASE STREQUAL "hold-of-an-action-the-map-does-not-have")
  run_headless(--frames 1 --input "1: hold fly")
elseif (CASE STREQUAL "vulkan-version")
  run_headless(--frames 1 --vulkan-version 1.1)
elseif (CASE STREQUAL "capabilities")
  run_headless(--frames 1)
elseif (CASE STREQUAL "vulkan-version-below-what-is-needed")
  run_headless(--frames 1 --vulkan-version 1.0)
else ()
  message(FATAL_ERROR "There is no case '${CASE}'")
endif ()

# Refused before a driver is looked for, so it is the same on a machine
# that cannot render
if (CASE STREQUAL "vulkan-version-below-what-is-needed")
  expect_exit_code(1)
  expect_output("Vulkan 1.0 was asked for, but the engine needs Vulkan 1.1 at least")
  return()
endif ()

# the script is checked against the input map before anything is rendered
if (CASE STREQUAL "hold-of-an-action-the-map-does-not-have")
  expect_exit_code(1)
  expect_output("'hold fly' names an action the input map does not have. It has: move, look, pause")
  return()
endif ()

# a machine that cannot render at all skips the test
string(FIND "${OUTPUT}" "Failed to initialize Vulkan" NO_VULKAN)
if (NOT NO_VULKAN EQUAL -1)
  message("SKIPPED: this machine cannot start the Vulkan renderer")
  message("${OUTPUT}")
  return()
endif ()

if (CASE STREQUAL "window-size-and-render-scale")
  expect_exit_code(0)
  expect_no_output("[error]")
  expect_no_output("[warning]")
  expect_image_size("shots/frame.png" 1280 720)
elseif (CASE STREQUAL "settings-menu-with-input")
  expect_exit_code(0)
  expect_output("Loading the user interface from assets://ui/settings.ui.yml")
  expect_output("Rendered 40 frames, stopping")
  expect_no_output("[error]")
  expect_no_output("[warning]")
  expect_image_size("shots/frame-0020.png" 1920 1080)
  expect_image_size("shots/frame-0040.png" 1920 1080)

  # the frame with the text typed and the list open differs from the one before
  file(SHA256 "${DIRECTORY}/shots/frame-0020.png" BEFORE)
  file(SHA256 "${DIRECTORY}/shots/frame-0040.png" AFTER)
  if (BEFORE STREQUAL AFTER)
    fail("Expected the input to change the frame")
  endif ()
elseif (CASE STREQUAL "pause-menu")
  expect_exit_code(0)
  expect_output("Rendered 40 frames, stopping")
  expect_no_output("[error]")
  expect_no_output("[warning]")
  expect_output("Loading the user interface from assets://ui/pause.ui.yml")
  expect_output("Unloading the user interface of assets://ui/pause.ui.yml")
  expect_image("shots/frame-0003.png")
  expect_image("shots/frame-0010.png")
  expect_image("shots/frame-0025.png")
  expect_image("shots/frame-0040.png")

  # the menu is in the frame after pause, gone after cancel, and back
  # after the next press. The world stands still under it, so the frame
  # without the menu is the one from before
  file(SHA256 "${DIRECTORY}/shots/frame-0003.png" BEFORE)
  file(SHA256 "${DIRECTORY}/shots/frame-0010.png" SHOWN)
  file(SHA256 "${DIRECTORY}/shots/frame-0025.png" CLOSED)
  file(SHA256 "${DIRECTORY}/shots/frame-0040.png" AGAIN)
  if (BEFORE STREQUAL SHOWN)
    fail("Expected pause to show the menu")
  endif ()
  if (NOT CLOSED STREQUAL BEFORE)
    fail("Expected the frame after the menu was closed to be the one from before it, with the world still")
  endif ()
  if (AGAIN STREQUAL CLOSED)
    fail("Expected the second press to show the menu again")
  endif ()
elseif (CASE STREQUAL "input-map-of-the-project")
  expect_exit_code(0)
  expect_output("Reading the input map from assets://input/default.input.yml")
  expect_no_output("[error]")
elseif (CASE STREQUAL "ui-scale")
  expect_exit_code(0)
  if (NOT PLAIN_EXIT_CODE STREQUAL "0")
    fail("Expected the run without --ui-scale to end with the exit code 0")
  endif ()
  expect_no_output("[error]")
  expect_image_size("shots/plain.png" 1920 1080)
  expect_image_size("shots/large.png" 1920 1080)

  file(SHA256 "${DIRECTORY}/shots/plain.png" PLAIN)
  file(SHA256 "${DIRECTORY}/shots/large.png" LARGE)
  if (PLAIN STREQUAL LARGE)
    fail("Expected --ui-scale to change the frame")
  endif ()
elseif (CASE STREQUAL "last-frame")
  expect_exit_code(0)
  expect_output("Rendered 3 frames, stopping")
  expect_image("shots/frame.png")
  expect_no_file("shots/frame-0003.png")
elseif (CASE STREQUAL "listed-frames")
  expect_exit_code(0)
  # the run is as long as the highest frame that was asked for
  expect_output("Rendered 3 frames, stopping")
  expect_image("shots/today/frame-0001.png")
  expect_image("shots/today/frame-0003.png")
  expect_no_file("shots/today/frame-0002.png")
  expect_no_file("shots/today/frame.png")
elseif (CASE STREQUAL "without-screenshot")
  expect_exit_code(0)
  expect_output("Rendered 2 frames, stopping")
  expect_no_file("shots")
elseif (CASE STREQUAL "screenshot-for-the-user")
  expect_exit_code(0)
  # where the folder of the user is below the home folder depends on the
  # platform
  file(GLOB_RECURSE SAVED RELATIVE "${DIRECTORY}" "${DIRECTORY}/home/frame.png")
  list(LENGTH SAVED COUNT)
  if (NOT COUNT EQUAL 1 OR NOT SAVED MATCHES "neon-engine/neon-runtime/shots/frame.png$")
    fail("Expected one image in the folder of the user, below ${DIRECTORY}/home, found '${SAVED}'")
  endif ()
  expect_image("${SAVED}")
elseif (CASE STREQUAL "user-interface")
  expect_exit_code(0)
  if (NOT PLAIN_EXIT_CODE STREQUAL "0")
    fail("Expected the run without a user interface to end with the exit code 0")
  endif ()
  expect_output("Loading the user interface from assets://ui/hud.ui.yml")
  expect_output("Loaded the font assets://fonts/inter/Inter-Regular.ttf")
  expect_no_output("[error]")
  expect_no_output("[warning]")
  expect_image("shots/plain.png")
  expect_image("shots/frame.png")

  # what is drawn on top is part of the frame that is saved
  file(SHA256 "${DIRECTORY}/shots/plain.png" PLAIN)
  file(SHA256 "${DIRECTORY}/shots/frame.png" WITH_USER_INTERFACE)
  if (PLAIN STREQUAL WITH_USER_INTERFACE)
    fail("Expected the frame with a user interface to differ from the one without")
  endif ()
elseif (CASE STREQUAL "user-interface-of-a-scene")
  expect_exit_code(0)
  expect_output("Loading the scene from assets://scenes/hud-demo.scene.yml")
  expect_output("Loading the user interface from assets://ui/hud.ui.yml")
  expect_no_output("[error]")
  expect_image("shots/frame.png")
elseif (CASE STREQUAL "user-interface-that-is-missing")
  # the run goes on without it and renders, says why, and fails all the same
  expect_exit_code(1)
  expect_output("assets://ui/missing.ui.yml: the file cannot be read")
  expect_output("The user interface assets://ui/missing.ui.yml cannot be used, nothing is shown from the start")
  expect_image("shots/frame.png")
elseif (CASE STREQUAL "vulkan-version")
  # what is asked for is the most that is used, and the log says what was
  expect_exit_code(0)
  expect_output(" in Vulkan 1.1. Vulkan 1.1 was asked for")
elseif (CASE STREQUAL "capabilities")
  # what the graphics card can do is logged, and without a window there
  # are no present modes to choose from
  expect_exit_code(0)
  expect_output("Textures up to ")
  expect_output("Present modes: none without a window")
  expect_output("Scene image of R16G16B16A16_SFLOAT: yes, sRGB textures: yes")
elseif (CASE STREQUAL "output-folder-cannot-be-used")
  # the run still renders, says what went wrong, and fails
  expect_exit_code(1)
  expect_output("cannot be used, output:// stays without a folder")
  expect_output("Rendered 1 frames, stopping")
  file(READ "${DIRECTORY}/taken" TAKEN)
  if (NOT TAKEN STREQUAL "a file, not a folder")
    fail("Expected the file that was in the way to be left as it was")
  endif ()
endif ()
